---
title: "`ciftiTools` Demo"
author: "Damon Pham & Amanda Mejia"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
  toc: true
  keep_md: true
vignette: >
  %\VignetteIndexEntry{`ciftiTools` Demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include=FALSE}
library(knitr)
knitr::opts_chunk$set(autodep = TRUE, cache = FALSE)
```

```{r}
# Check if package installed. If not, install it.
if(!require('ciftiTools', quietly=TRUE)){
  install.packages('ciftiTools')
  # devtools::install_github('mandymejia/ciftiTools') # development version
}

library(ciftiTools)
```

```{r}
# Replace '~/Desktop/workbench' with the actual path to 
#   the Connectome Workbench folder on your computer.
#   If successful, the path to the Workbench executable will be printed.
ciftiTools.setOption('wb_path', '~/Applications')
```

```{r}
cifti_fnames <- ciftiTools.files()$cifti
surfL_fname <- ciftiTools.files()$surf["left"]
surfR_fname <- ciftiTools.files()$surf["right"]
```

```{r}
basename(cifti_fnames["dtseries"])
xii <- read_xifti(cifti_fnames["dtseries"])
```


```{r}
library(rgl)
rgl::setupKnitr()

# Sometimes the first OpenGL window does not render properly.
rgl::open3d(); rgl::close3d()

# These are also required.
library(manipulateWidget)
library(ggpubr)
```

```{r, fig.cap="dtseries file; first column; sequential palette", rgl=TRUE, format="jpg", fig.height=4.2, fig.width=5.5}
# Normally `cex.title` doesn't need to be set, as it defaults to a good choice.
#   But when knitting static images this way, the default becomes a bit too big
#   based on how knitting works.
view_xifti_surface(xii, idx=1, zlim=c(1,2), title='color_mode = "sequential"', cex.title=1.3)
```

```{r fig.height=4.2, fig.width=5.5}
xii <- read_cifti(cifti_fnames["dscalar"]) # no GIFTI included, so the default inflated surface is used.
view_xifti_surface(
  xii, idx=1:2, zlim=c(0,5), color_mode = "diverging",
  title='color_mode = "diverging"', cex.title=1.3
)
```

```{r, fig.cap="dlabel file; first label; palette from label metadata", rgl=TRUE, format="jpg", fig.height=4.2, fig.width=5.5}
view_xifti_surface(
  read_cifti(cifti_fnames["dlabel"]), 
  # Interactively, a color legend that displays the label names will also be printed.
  legend_ncol=5, 
  title='color_mode = "qualitative"', cex.title=1.3
)
```
